### PR TITLE
Article-id logic

### PR DESCRIPTION
**Pull request by fred-atherden**

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
We'll definitely need test cases for this. As we're looking at 'info' rather than warnings or errors, we'll need to review the test suite again (since it treats everything as an error). Probably worth looking at using XSpec instead.

**Comment by fred-atherden** [comment]
Added an example XSpec test which passes locally (firing tests in patterns `year`, `year_parent`, and `article-id-logic`). 

If you want to continue with this let me know and I can go about adding the rest of the tests (or incorporating the existing ones here).

**Comment by fred-atherden** [comment]
XSpec unit testing now in use at https://github.com/elifesciences/eLife-JATS-schematron (using Travis) so we could borrow from that (if at all useful).

**Comment by fred-atherden** [comment]
Added XSpec unit testing to `data-model` branch so closing this pr.

**Pull request closed without merging**
